name=Boardoza INA250A Current Sensor
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <eray.eroglu@boardoza.com>
sentence=Library for Boardoza INA250A Bidirectional Current Sensor.
paragraph=This library provides an easy-to-use API for measuring bidirectional current using the INA250A current-shunt monitor. It handles ADC value conversions and scaling based on the device's integrated precision shunt resistor and specific gain. The library is designed for quick integration into Arduino and PlatformIO projects requiring highly accurate, zero-drift current measurements for power monitoring, system protection, and load diagnostics.
category=Sensors
url=https://github.com/Boardoza/Boardoza_INA250A1_Precision_Current_Sense_Breakout_Board
architectures=*